// flow-typed signature: f44e38c9a194da768b77193cc61b760c
// flow-typed version: <<STUB>>/eslint-config-fusion_v^4.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-fusion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-fusion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-fusion/rules/imports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-fusion/index' {
  declare module.exports: $Exports<'eslint-config-fusion'>;
}
declare module 'eslint-config-fusion/index.js' {
  declare module.exports: $Exports<'eslint-config-fusion'>;
}
declare module 'eslint-config-fusion/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-fusion/rules/imports'>;
}
