// flow-typed signature: 8b414daa8999147d7efb8e7d3ee77f91
// flow-typed version: <<STUB>>/eslint-plugin-cup_v^2.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-cup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-cup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-cup/lib/rules/no-undef' {
  declare module.exports: any;
}

declare module 'eslint-plugin-cup/test/lib/rules/no-undef' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-cup/index' {
  declare module.exports: $Exports<'eslint-plugin-cup'>;
}
declare module 'eslint-plugin-cup/index.js' {
  declare module.exports: $Exports<'eslint-plugin-cup'>;
}
declare module 'eslint-plugin-cup/lib/rules/no-undef.js' {
  declare module.exports: $Exports<'eslint-plugin-cup/lib/rules/no-undef'>;
}
declare module 'eslint-plugin-cup/test/lib/rules/no-undef.js' {
  declare module.exports: $Exports<'eslint-plugin-cup/test/lib/rules/no-undef'>;
}
