// flow-typed signature: bb3cfbb9196bdeceb0f787d50c929187
// flow-typed version: <<STUB>>/isomorphic-git_v^0.39.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-git/cli' {
  declare module.exports: any;
}

declare module 'isomorphic-git/dist/bundle.umd.min' {
  declare module.exports: any;
}

declare module 'isomorphic-git/dist/for-future/isomorphic-git/index' {
  declare module.exports: any;
}

declare module 'isomorphic-git/dist/for-future/isomorphic-git/internal-apis' {
  declare module.exports: any;
}

declare module 'isomorphic-git/dist/for-node/isomorphic-git/index' {
  declare module.exports: any;
}

declare module 'isomorphic-git/dist/for-node/isomorphic-git/internal-apis' {
  declare module.exports: any;
}

declare module 'isomorphic-git/dist/internal.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-git/cli.js' {
  declare module.exports: $Exports<'isomorphic-git/cli'>;
}
declare module 'isomorphic-git/dist/bundle.umd.min.js' {
  declare module.exports: $Exports<'isomorphic-git/dist/bundle.umd.min'>;
}
declare module 'isomorphic-git/dist/for-future/isomorphic-git/index.js' {
  declare module.exports: $Exports<'isomorphic-git/dist/for-future/isomorphic-git/index'>;
}
declare module 'isomorphic-git/dist/for-future/isomorphic-git/internal-apis.js' {
  declare module.exports: $Exports<'isomorphic-git/dist/for-future/isomorphic-git/internal-apis'>;
}
declare module 'isomorphic-git/dist/for-node/isomorphic-git/index.js' {
  declare module.exports: $Exports<'isomorphic-git/dist/for-node/isomorphic-git/index'>;
}
declare module 'isomorphic-git/dist/for-node/isomorphic-git/internal-apis.js' {
  declare module.exports: $Exports<'isomorphic-git/dist/for-node/isomorphic-git/internal-apis'>;
}
declare module 'isomorphic-git/dist/internal.umd.min.js' {
  declare module.exports: $Exports<'isomorphic-git/dist/internal.umd.min'>;
}
