// flow-typed signature: 245bacba8502d486ad3ae3b9ef012d15
// flow-typed version: <<STUB>>/recast_v^0.16.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recast/lib/comments' {
  declare module.exports: any;
}

declare module 'recast/lib/fast-path' {
  declare module.exports: any;
}

declare module 'recast/lib/lines' {
  declare module.exports: any;
}

declare module 'recast/lib/mapping' {
  declare module.exports: any;
}

declare module 'recast/lib/options' {
  declare module.exports: any;
}

declare module 'recast/lib/parser' {
  declare module.exports: any;
}

declare module 'recast/lib/patcher' {
  declare module.exports: any;
}

declare module 'recast/lib/printer' {
  declare module.exports: any;
}

declare module 'recast/lib/types' {
  declare module.exports: any;
}

declare module 'recast/lib/util' {
  declare module.exports: any;
}

declare module 'recast/main' {
  declare module.exports: any;
}

declare module 'recast/parsers/_babel_options' {
  declare module.exports: any;
}

declare module 'recast/parsers/acorn' {
  declare module.exports: any;
}

declare module 'recast/parsers/babel' {
  declare module.exports: any;
}

declare module 'recast/parsers/babylon' {
  declare module.exports: any;
}

declare module 'recast/parsers/esprima' {
  declare module.exports: any;
}

declare module 'recast/parsers/flow' {
  declare module.exports: any;
}

declare module 'recast/parsers/typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recast/lib/comments.js' {
  declare module.exports: $Exports<'recast/lib/comments'>;
}
declare module 'recast/lib/fast-path.js' {
  declare module.exports: $Exports<'recast/lib/fast-path'>;
}
declare module 'recast/lib/lines.js' {
  declare module.exports: $Exports<'recast/lib/lines'>;
}
declare module 'recast/lib/mapping.js' {
  declare module.exports: $Exports<'recast/lib/mapping'>;
}
declare module 'recast/lib/options.js' {
  declare module.exports: $Exports<'recast/lib/options'>;
}
declare module 'recast/lib/parser.js' {
  declare module.exports: $Exports<'recast/lib/parser'>;
}
declare module 'recast/lib/patcher.js' {
  declare module.exports: $Exports<'recast/lib/patcher'>;
}
declare module 'recast/lib/printer.js' {
  declare module.exports: $Exports<'recast/lib/printer'>;
}
declare module 'recast/lib/types.js' {
  declare module.exports: $Exports<'recast/lib/types'>;
}
declare module 'recast/lib/util.js' {
  declare module.exports: $Exports<'recast/lib/util'>;
}
declare module 'recast/main.js' {
  declare module.exports: $Exports<'recast/main'>;
}
declare module 'recast/parsers/_babel_options.js' {
  declare module.exports: $Exports<'recast/parsers/_babel_options'>;
}
declare module 'recast/parsers/acorn.js' {
  declare module.exports: $Exports<'recast/parsers/acorn'>;
}
declare module 'recast/parsers/babel.js' {
  declare module.exports: $Exports<'recast/parsers/babel'>;
}
declare module 'recast/parsers/babylon.js' {
  declare module.exports: $Exports<'recast/parsers/babylon'>;
}
declare module 'recast/parsers/esprima.js' {
  declare module.exports: $Exports<'recast/parsers/esprima'>;
}
declare module 'recast/parsers/flow.js' {
  declare module.exports: $Exports<'recast/parsers/flow'>;
}
declare module 'recast/parsers/typescript.js' {
  declare module.exports: $Exports<'recast/parsers/typescript'>;
}
